version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: stock-photo-db
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: local
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/migration/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 5s
      timeout: 1m
      retries: 5
      start_period: 10s

  app:
    container_name: stock-photo-app
    build:
      context: .
      dockerfile: ./services/app/docker/Dockerfile.local
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./:/app
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy

  admin:
    container_name: stock-photo-admin
    build:
      context: .
      dockerfile: ./services/admin/docker/Dockerfile.local
    ports:
      - "8001:8000"
    tty: true
    volumes:
      - ./:/app
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
