version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: stock-photo-db
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: passowrd
      TZ: Asia/Tokyo
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./src/migration/init:/docker-entrypoint-initdb.d
      
  app:
    container_name: stock-photo-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    ports:
      - "8000:8000"
    tty: true
    volumes:
      - ./:/app
    env_file:
      - .env.local
    depends_on:
      - db
