// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package oapi

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// PostApiImagesUploadMultipartBody defines parameters for PostApiImagesUpload.
type PostApiImagesUploadMultipartBody struct {
	// File Image file
	File *openapi_types.File `json:"file,omitempty"`

	// Title Title of the image
	Title *string `json:"title,omitempty"`
}

// PostApiImagesUploadMultipartRequestBody defines body for PostApiImagesUpload for multipart/form-data ContentType.
type PostApiImagesUploadMultipartRequestBody PostApiImagesUploadMultipartBody
