// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package oapi

// PostApiImagesUploadMultipartBody defines parameters for PostApiImagesUpload.
type PostApiImagesUploadMultipartBody struct {
	// File 画像ファイル
	File *interface{} `json:"file,omitempty"`

	// Title 画像タイトル
	Title *string `json:"title,omitempty"`
}

// PostApiImagesUploadMultipartRequestBody defines body for PostApiImagesUpload for multipart/form-data ContentType.
type PostApiImagesUploadMultipartRequestBody PostApiImagesUploadMultipartBody
