definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
  enum.ImageApprovalStatus:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - PENDING
    - APPROVED
    - REJECTED
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.Image:
    properties:
      approvalStatus:
        $ref: '#/definitions/enum.ImageApprovalStatus'
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      detailUrl:
        type: string
      id:
        type: integer
      purchaseUrl:
        type: string
      thumbnailUrl:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
info:
  contact: {}
  description: StockPhoto API ドキュメント
  title: StockPhoto API Documents
  version: "1.0"
paths:
  /api/images:
    get:
      description: アップロードされた画像の一覧を返す
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Image'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: 画像一覧取得
      tags:
      - images
  /api/images/upload:
    post:
      consumes:
      - multipart/form-data
      description: リクエストされた画像をGCSにアップロードする
      parameters:
      - description: 画像タイトル
        in: formData
        name: title
        required: true
        type: string
      - description: 画像ファイル
        in: formData
        name: file
        required: true
        type: file
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: 画像アップロード
      tags:
      - images
swagger: "2.0"
