FROM golang:1.20-bullseye

ENV TZ=Asia/Tokyo

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest
RUN go install -tags 'mysql' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY stock-photo-test-gcp-key.json ./stock-photo-test-gcp-key.json
ENV GOOGLE_APPLICATION_CREDENTIALS ./stock-photo-test-gcp-key.json

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", "./docker/.air.toml"]
