openapi: 3.0.0
info:
  contact: {}
  description: StockPhoto API ドキュメント
  title: StockPhoto API Documents
  version: "1.0"
paths:
  /api/images/upload:
    post:
      description: リクエストされた画像をGCSにアップロードする
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  description: 画像タイトル
                  type: string
                file:
                  description: 画像ファイル
                  type: string
                  format: binary
              required:
                - title
                - file
        required: true
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/echo.HTTPError"
      summary: 画像アップロード
      tags:
        - images
components:
  schemas:
    echo.HTTPError:
      properties:
        message: {}
      type: object
