definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
info:
  contact: {}
  description: StockPhoto API ドキュメント
  title: StockPhoto API Documents
  version: "1.0"
paths:
  /api/images/upload:
    post:
      consumes:
      - multipart/form-data
      description: リクエストされた画像をGCSにアップロードする
      parameters:
      - description: 画像ファイル
        in: formData
        name: file
        required: true
        type: file
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/echo.HTTPError'
      summary: 画像アップロード
      tags:
      - images
swagger: "2.0"
