openapi: 3.1.0
definitions:
  echo.HTTPError:
    properties:
      message: {}
    type: object
info:
  contact: {}
  description: StockPhoto API ドキュメント
  title: StockPhoto API Documents
  version: "1.0"
paths:
  /api/images/upload:
    post:
      consumes:
        - multipart/form-data
      description: リクエストされた画像をGCSにアップロードする
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Title of the image
                file:
                  type: string
                  format: binary
                  description: Image file
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: "#/definitions/echo.HTTPError"
      summary: 画像アップロード
      tags:
        - images
